language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
script:
  - npm test
  - npm run build
  - codecov
deploy:
  provider: surge
  skip_cleanup: true
  domain: http://pocket-clone.surge.sh/
  project: ./build/
on:
  branch: master
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION